// The coat rig (COMBAT.md §14.2): Milo's proportions, 16 × 20 at rest, in a 32 × 28 fight frame with
// his feet at (16, 26). Key poses are drawn by hand at body size and placed by sprites-party.js;
// the rest of each clip is derived by pose operations (breathe, shift, lift, nudge, squash).
//
// Milo carries the Hooklight, his hand lantern, in every fight pose: it's his light, his knacks
// (Mote, Flare) and, swung, his light weapon. Its glass is drawn in placeholder keys (a butter,
// d honey, i cream, y its bronze frame), which become palette keys when the frame is built and
// mark it as held, so a genre dresses his coat and scarf and never the lantern.
//
// Pose fields: rows (grid), at ([dx, dy] of the grid's top-left from the standing sprite's),
// split (the scarf row in the grid: the head is above it), anchors (grid points: head, handL,
// handR, back; handR is the hand toward his facing).
import { grid, MILO, stamp } from '../sprites.js';

const P = (rows, at, split, anchors) => Object.freeze({ rows: Object.freeze(rows), at: Object.freeze(at), split, anchors: Object.freeze(anchors) });

// ---------- side poses (facing right) ----------

const READY = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.....
  .ommmmmmttttoto.....
  .ommmmmmttttoto.....
  .ommmmmtttttkto.....
  ..ommmmtttttto......
  ...orrrrrrrroooo....
  ..orRUUUUUUbUUtto...
  ...ouUUUUUUboooo....
  ...ouUUUUUUbooyyyo..
  ...ouUUUUUUbooiado..
  ...ouUUUUUUbooaado..
  ...oooooooooooyyyo..
  ...oBBo.oBBo..ooo...
  ...oooo.oooo........
`);

// Walking: his own stride frames with the lantern held out, as in READY (the arm patch sits over the
// sleeve and hand he walks with).
const HOLD_SIDE = grid(`
  ............oooo....
  ...........bUUtto...
  ...........boooo....
  ...........booyyyo..
  ...........booiado..
  ...........booaado..
  ............ooyyyo..
  ..............ooo...
`);
const handPatch = (rows) => stamp(stamp(rows.map((r) => `${r}....`), ['...ouUUUUUUbo'], 0, 14), HOLD_SIDE, 0, 11);

// Melee, 1: anticipation. He draws the lantern back past his hip and settles his weight.
const MELEE_A = grid(`
  ......oooooo........
  ....oommmmmmoo......
  ...ommmmmmmmmmo.....
  ..ommmbbmmmmmmmo....
  ..ommbbmmmmmmmmo....
  ..ommmmmmmttttmo....
  ..ommmmmmtttttto....
  ..ommmmmmttttoto....
  ..ommmmmmttttoto....
  ..ommmmmtttttkto....
  ...ommmmtttttto.....
  ....orrrrrrrro......
  ...orRUUUUUUbo......
  oooouUUUUUUUbo......
  ottUUUUUUUUUbo......
  oyoouUUUUUUUbo......
  yyyoouUUUUUbo.......
  iadoooooooooo.......
  aadoBBo..oBBo.......
  yyyoooo..oooo.......
`);

// Melee, 2: wind-up. The lantern swings up behind his head; he leans into the step.
const MELEE_B = grid(`
  ooooo...............
  oyyyo..oooooo.......
  oiado.oommmmmmoo....
  oaado.ommmmmmmmmmo..
  oyyyooommmbbmmmmmmo.
  .ooo..ommbbmmmmmmmo.
  ..ott.ommmmmmmttttmo
  ...oUoommmmmmtttttto
  ....oUommmmmmttttoto
  .....oUommmmmttttoto
  ......oUommmtttttkto
  .......oUommmtttttto
  ........oorrrrrrrro.
  .......orRUUUUUUbo..
  ........ouUUUUUUbo..
  ........ouUUUUUUbo..
  ........ouUUUUUUbo..
  ........oooooooooo..
  .......oBBo...oBBo..
  .......oooo...oooo..
`);

// Melee, 3: the strike. Swung round and down in front at full reach, a streak of light behind it.
const MELEE_C = grid(`
  .....oooooo.............
  ...oommmmmmoo...........
  ..ommmmmmmmmmo..........
  .ommmbbmmmmmmmo.........
  .ommbbmmmmmmmmo.........
  .ommmmmmmttttmo.........
  .ommmmmmtttttto.........
  .ommmmmmttttoto.........
  .ommmmmmttttoto.........
  .ommmmmtttttkto....i....
  ..ommmmtttttto......a...
  ...orrrrrrrroooooo...a..
  ..orRUUUUUUbUUUUUtto.a..
  ...ouUUUUUUbooooooooyyyo
  ...ouUUUUUUbo....oiaado.
  ...ouUUUUUUbo....oaaado.
  ...ouUUUUUUbo....oyyyyo.
  ...oooooooooo.....oooo..
  .oBBo.....oBBo..........
  .oooo.....oooo..........
`);

// Ranged, 1: aim. The lantern held up at eye height, arm out, looking along it.
const RANGED_A = grid(`
  .....oooooo..........
  ...oommmmmmoo........
  ..ommmmmmmmmmo.......
  .ommmbbmmmmmmmo.oyyyo
  .ommbbmmmmmmmmo.oiado
  .ommmmmmmttttmo.oaado
  .ommmmmmtttttto.oyyyo
  .ommmmmmttttoto..ooo.
  .ommmmmmttttoto..ott.
  .ommmmmtttttkto.oUUo.
  ..ommmmtttttto.oUUo..
  ...orrrrrrrrooUUo....
  ..orRUUUUUUbUUoo.....
  ...ouUUUUUUbooo......
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...oooooooooo........
  ..oBBo...oBBo........
  ..oooo...oooo........
`);

// Ranged, 2: release. Thrust forward, the mote leaving the glass in a small burst.
const RANGED_B = grid(`
  ....oooooo.............
  ..oommmmmmoo...........
  .ommmmmmmmmmo..........
  ommmbbmmmmmmmo.......i.
  ommbbmmmmmmmmo....i....
  ommmmmmmttttmo.........
  ommmmmmtttttto..oooo..i
  ommmmmmttttoto.oyyyyo..
  ommmmmmttttoto.oiaado..
  ommmmmtttttkto.oaaado.i
  .ommmmtttttto..oyyyyo..
  ..orrrrrrrrooooottooi..
  .orRUUUUUUbUUUUUtto....
  ..ouUUUUUUbooooooo.....
  ..ouUUUUUUbo...........
  ..ouUUUUUUbo...........
  ..ouUUUUUUbo...........
  ..oooooooooo...........
  oBBo.....oBBo..........
  oooo.....oooo..........
`);

// Cast, 1: gather. Both hands close the lantern to his chest and its light wells up round it.
const CAST_A = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.....
  .ommmmmmttttoto..i..
  .ommmmmmttttoto.....
  .ommmmmtttttkto.a...
  ..ommmmtttttto.....i
  ...orrrrrrrrooooo...
  ..orRUUUUUUbUoyyyo..
  ...ouUUUUUUtoiaado.a
  ...ouUUUUUUtoaaado..
  ...ouUUUUUUboyyyyo..
  ...ouUUUUUUbooooo.i.
  ...oooooooooo.......
  ...oBBo.oBBo........
  ...oooo.oooo........
`);

// Cast, 2: release. Lifted out and up at arm's length, rays going off the glass.
const CAST_B = grid(`
  .............a...i...
  .....oooooo.....a....
  ...oommmmmmoo.i.oooo.
  ..ommmmmmmmmmo.oyyyyo
  .ommmbbmmmmmmmooiaado
  .ommbbmmmmmmmmooaaado
  .ommmmmmmttttmooyyyyo
  .ommmmmmttttttootoo.i
  .ommmmmmttttotoUUo...
  .ommmmmmttttotoUo....
  .ommmmmtttttkoUo..a..
  ..ommmmttttttoUo.....
  ...orrrrrrrroUo......
  ..orRUUUUUUbUo.......
  ...ouUUUUUUboo.......
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...oooooooooo........
  ...oBBo.oBBo.........
  ...oooo.oooo.........
`);

// Gesture: the free hand up and out (a whistle, a tonic offered, a verdict); the lantern hangs behind.
const GESTURE = grid(`
  ......oooooo.........
  ....oommmmmmoo.......
  ...ommmmmmmmmmo......
  ..ommmbbmmmmmmmo.....
  ..ommbbmmmmmmmmo.....
  ..ommmmmmmttttmo.oo..
  ..ommmmmmtttttto.ott.
  ..ommmmmmttttoto.ott.
  ..ommmmmmttttoto.oto.
  ..ommmmmtttttkto.oUo.
  ...ommmmtttttto.oUUo.
  ....orrrrrrrrooUUo...
  ...orRUUUUUUbUUoo....
  ..oouUUUUUUUbo.......
  .ottUUUUUUUUbo.......
  .oyyooUUUUUUbo.......
  oyyyoouUUUUUbo.......
  oiadoooooooooo.......
  oaado.oBBo.oBBo......
  oyyyo.oooo.oooo......
`);

// Hit: jolted back, eyes squeezed shut, the lantern swinging wide.
const HIT = grid(`
  ...oooooo...........
  .oommmmmmoo.........
  ommmmmmmmmmo........
  ommbbmmmmmmmo.......
  ombbmmmmmmmmo.......
  ommmmmmmttttmo......
  ommmmmmtttttto......
  ommmmmmttotttoo.....
  ommmmmmtttotoo......
  ommmmmtttttkto......
  .ommmmtttttto.......
  ..orrrrrrrro........
  .orRUUUUUUbooo......
  ..ouUUUUUUbUtto.....
  ..ouUUUUUUbooooo....
  ..ouUUUUUUbo.oyyyo..
  ..ouUUUUUUbo.oiado..
  ..oooooooooo.oyyyo..
  ...oBBo.oBBo..ooo...
  ...oooo.oooo........
`);

// Dodge: a quick lean back off the front foot, the lantern pulled in out of reach.
const DODGE = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.....
  .ommmmmmttttoto.....
  .ommmmmmttttoto.....
  .ommmmmtttttkto.....
  ..ommmmtttttto......
  ....orrrrrrrro......
  ....orRUUUUUbooo....
  .....ouUUUUUbtto....
  .....ouUUUUUboyyyo..
  .....ouUUUUUboiado..
  ......ouUUUUboaado..
  ......ooooooooyyyo..
  ....oBBo..oBBoooo...
  ....oooo..oooo......
`);

// Brace: crouched low behind a raised arm, the lantern tucked in against his coat.
const BRACE = grid(`
  ....................
  ....................
  ....................
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmoooo..
  .ommmmmmtttttoUUUo..
  .ommmmmmttttoUUtto..
  .ommmmmmtttootUooo..
  ..ommmmtttttoUUo....
  ...orrrrrrrrooo.....
  ..orRUUUUUoyyyo.....
  ..ouUUUUUUoiado.....
  ..ouUUUUUUoaado.....
  ..oooooooooyyyo.....
  .oBBBo.oBBBooo......
  .ooooo.ooooo........
`);

// Jump: knees tucked, arms up, the lantern swung high for balance.
const JUMP = grid(`
  ..............ooo...
  .....oooooo..oyyyo..
  ...oommmmmmoooiado..
  ..ommmmmmmmmmoaado..
  .ommmbbmmmmmmoyyyo..
  .ommbbmmmmmmmmooo...
  .ommmmmmmttttmott...
  .ommmmmmttttttoUo...
  .ommmmmmttttotoUo...
  .ommmmmmttttotUo....
  .ommmmmtttttkUo.....
  ..ommmmttttttUo.....
  ...orrrrrrrrUo......
  ..orRUUUUUUbo.......
  ..ouUUUUUUUbo.......
  ..ouUUUUUUUbo.......
  ..ooooooooooo.......
  ...oBBoBBBo.........
  ...ooooooo..........
  ....................
`);

// Tumbled: knocked flat on his back, boots in the air, the lantern rolled clear. Lying down, his
// coat is beside his head rather than below it, so the split sits above the whole of him (row 10).
const TUMBLE = grid(`
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ..................oo....
  .................oBBo...
  ......oooo.......oBBo...
  ....oommmmoo....oBBoo...
  ...ommmbbmmmooooouuo....
  ..ommbbmmmmmorrrUUUUoo..
  ..ommmmmmmmmorUUUUUUUo..
  .ommmmmmmmmmorUUUUUUbo..
  .ommmmmmtttoorUUUUUbo...
  .omtttottkto.oooooooo...
  .oootttttoo..oyyyo......
  ...ooooooo...oiado......
  .............ooooo......
`);

// Offline, 1: the wobble. Eyes gone to swirls, the lantern sagging, a knee going.
const WOBBLE = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.....
  .ommmmmmtttoooo.....
  .ommmmmmtttoto......
  .ommmmmtttttkto.....
  ..ommmmtttttto......
  ...orrrrrrrro.......
  ..orRUUUUUUbo.......
  ...ouUUUUUUbo.......
  ...ouUUUUUUbo.......
  ...ouUUUUUUtto......
  ...ouUUUUUUbooyyyo..
  ...ooooooooooaiado..
  ....oBBooBBo.oyyyo..
  ....oooooooo..ooo...
`);

// Offline, 2: dozing where he sat down: legs out in front, head nodded onto his scarf, the lantern
// set down beside him and turned low (honey glass).
const DOZE = grid(`
  ......................
  ......................
  ......................
  ......................
  ......................
  ......oooooo..........
  ....oommmmmmoo........
  ...ommmmmmmmmmo.......
  ..ommmbbmmmmmmmo......
  ..ommbbmmmmmmmmo......
  ..ommmmmmmmmmmmo......
  ..ommmmmmmtttttmo.....
  ..ommmmmmmttttoto.....
  ..ommmmmmtttttkto.....
  ...ommmmtttttttoo.....
  ...orrrrrrrrrroo......
  ..orRUUUUUUUUbo..oyyyo
  ..ouUUUUUUUUtto..oddyo
  ..ouUUUUUUUUBBBooyyyyo
  ..ooooooooooBBBo.oooo.
`);

// Item: a cordial from his satchel, tipped up to drink; the lantern low in the other hand.
const ITEM = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.oo..
  .ommmmmmmttttmookko.
  .ommmmmmttttttokcko.
  .ommmmmmttttottokko.
  .ommmmmmttttotootoo.
  .ommmmmtttttkttoUo..
  ..ommmmttttttooUo...
  ...orrrrrrrroUUo....
  ..orRUUUUUUbUUo.....
  ...ouUUUUUUboo......
  ..oouUUUUUUbo.......
  .ottUUUUUUUbo.......
  oyyyoUUUUUUbo.......
  oiadooooooooo.......
  oaadoBBo.oBBo.......
  oyyyooooooooo.......
`);

// Camp: sat on a stump (the scene draws the stump), legs dangling, the lantern on his knee.
const CAMP_SIT = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.....
  .ommmmmmttttoto.....
  .ommmmmmttttoto.....
  .ommmmmtttttkto.....
  ..ommmmtttttto......
  ...orrrrrrrro.......
  ..orRUUUUUUbooo.....
  ...ouUUUUUUtoyyyo...
  ...ouUUUUUUooiado...
  ...ouUUUUUUUUoooo...
  ...ooooooooUUUUUo...
  ..........ooooBBo...
  .............oBBo...
  .............oooo...
`);

// Camp: talking at the fire, a hand up to make the point.
const CAMP_TALK = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.oo..
  .ommmmmmttttoto.ott.
  .ommmmmmttttoto.oto.
  .ommmmmtttttkttoUo..
  ..ommmmttttttooUo...
  ...orrrrrrrroUUo....
  ..orRUUUUUUbUoo.....
  ...ouUUUUUUbo.......
  ...ouUUUUUUbooyyyo..
  ...ouUUUUUUUUoiado..
  ...ooooooooUUUoooo..
  ..........ooooBBo...
  .............oBBo...
  .............oooo...
`);

// Camp job: polishing the lantern on his lap with a corner of his scarf.
const CAMP_JOB = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.....
  .ommmmmmtttttoo.....
  .ommmmmmttttoto.....
  .ommmmmtttttkto.....
  ..ommmmtttttto......
  ...orrrrrrrroooo....
  ..orRUUUUUUbrrRo....
  ...ouUUUUUUoyyyoo...
  ...ouUUUUUUoiadtto..
  ...ouUUUUUUoaadooo..
  ...ooooooooUyyyUo...
  ..........ooooBBo...
  .............oBBo...
  .............oooo...
`);

// ---------- Milo's own (COMBAT.md §14.2: Scarf, Raise the lantern, the Wayward step) ----------

// Scarf, 1: Tamsin's too-long scarf flung out at arm's length toward whoever he's pulling in.
const SCARF_A = grid(`
  .....oooooo.............
  ...oommmmmmoo...........
  ..ommmmmmmmmmo..........
  .ommmbbmmmmmmmo.........
  .ommbbmmmmmmmmo.........
  .ommmmmmmttttmo.........
  .ommmmmmtttttto.........
  .ommmmmmttttoto.........
  .ommmmmmttttoto.........
  .ommmmmtttttkto.........
  ..ommmmtttttto..oooooo..
  ...orrrrrrrrooorrrrrrro.
  ..orRUUUUUUbUUttRRRRRRo.
  ...ouUUUUUUbooooooooRRo.
  ...ouUUUUUUbo.......oro.
  ...ouUUUUUUbo.......oRo.
  ...ouUUUUUUbo........o..
  ...oooooooooo...........
  ..oBBo...oBBo...........
  ..oooo...oooo...........
`);

// Scarf, 2: hauling it back in, leaning on his heels, the scarf in a loop.
const SCARF_B = grid(`
  ...oooooo...........
  .oommmmmmoo.........
  ommmmmmmmmmo........
  ommbbmmmmmmmo.......
  ombbmmmmmmmmo.......
  ommmmmmmttttmo......
  ommmmmmtttttto......
  ommmmmmttttoto......
  ommmmmmttttoto......
  ommmmmtttttkto.oooo.
  .ommmmtttttto.orrRRo
  ..orrrrrrrrroorooRRo
  .orRUUUUUUbUtto..oRo
  ..ouUUUUUUbooooooRRo
  ..ouUUUUUUbo.oRRRRo.
  ..ouUUUUUUbo..oooo..
  ..ouUUUUUUbo........
  ..oooooooooo........
  .oBBo...oBBo........
  .oooo...oooo........
`);

// Raise the lantern, 1: lifting it with both hands.
const RAISE_A = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .ommmmmmmttttmo.....
  .ommmmmmtttttto.....
  .ommmmmmttttoto.....
  .ommmmmmttttotooooo.
  .ommmmmtttttktoyyyo.
  ..ommmmttttttoiaado.
  ...orrrrrrrrooaaado.
  ..orRUUUUUUbUoyyyyo.
  ...ouUUUUUUtUoottoo.
  ...ouUUUUUUbooo.....
  ...ouUUUUUUbo.......
  ...ouUUUUUUbo.......
  ...oooooooooo.......
  ...oBBo.oBBo........
  ...oooo.oooo........
`);

// Raise the lantern, 2: held high overhead, the light thrown wide.
const RAISE_B = grid(`
  ..a..........ooo.....
  ............oyyyo..i.
  .....i......oiado....
  ............oaado.a..
  ............oyyyo....
  .............otto....
  .....oooooo...oUo....
  ...oommmmmmoo.oUo....
  ..ommmmmmmmmmooUo....
  .ommmbbmmmmmmmoUo....
  .ommbbmmmmmmmmoUo....
  .ommmmmmmttttmoUo....
  .ommmmmmttttttoUo....
  .ommmmmmttttotoUo....
  .ommmmmmttttotoUo....
  .ommmmmtttttktoUo....
  ..ommmmttttttoUo.....
  ...orrrrrrrroUo......
  ..orRUUUUUUbUo.......
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...oooooooooo........
  ...oBBo.oBBo.........
  ...oooo.oooo.........
`);

// The Wayward step, 1: the mote sent ahead, the lantern pointed after it.
const WAYWARD_A = grid(`
  .....oooooo..........
  ...oommmmmmoo........
  ..ommmmmmmmmmo.......
  .ommmbbmmmmmmmo......
  .ommbbmmmmmmmmo......
  .ommmmmmmttttmo......
  .ommmmmmtttttto..a..i
  .ommmmmmttttoto.ooo..
  .ommmmmmttttotooyyyo.
  .ommmmmtttttktoiaado.
  ..ommmmttttttoaaado.a
  ...orrrrrrrrooyyyyo..
  ..orRUUUUUUbUoottoo..
  ...ouUUUUUUbooooo....
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...ouUUUUUUbo........
  ...oooooooooo........
  ..oBBo...oBBo........
  ..oooo...oooo........
`);

// The Wayward step, 2: stepping into the light, a trail of it left behind him.
const WAYWARD_B = grid(`
  ...........oooooo.......
  .........oommmmmmoo.....
  ........ommmmmmmmmmo....
  .......ommmbbmmmmmmmo...
  ..i....ommbbmmmmmmmmo...
  .......ommmmmmmttttmo...
  ..a.i..ommmmmmtttttto...
  .......ommmmmmttttoto...
  .a..a..ommmmmmttttoto...
  .......ommmmmtttttkto...
  i..a....ommmmtttttto....
  .........orrrrrrrroooo..
  .a.i....orRUUUUUUbUUtto.
  .........ouUUUUUUboooo..
  ..a..i...ouUUUUUUbyyyo..
  .........ouUUUUUUbiado..
  a..a.....ouUUUUUUboyyo..
  .........oooooooooooo...
  ..i...oBBo....oBBo......
  ......oooo....oooo......
`);

// ---------- front poses ----------

// Standing, facing you, the lantern hung at his side.
const READY_FRONT = stamp(MILO.down[0].map((r) => `${r}....`), grid(`
  ..............o.....
  ............ooyyyo..
  ...........toiaado..
  ............oaaado..
  ............oyyyyo..
  .............oooo...
`), 0, 14);

const WALK_FRONT = MILO.down.map((rows) => stamp(rows.map((r) => `${r}....`), grid(`
  ..............o.....
  ............ooyyyo..
  ...........toiaado..
  ............oaaado..
  ............oyyyyo..
  .............oooo...
`), 0, 14));

// Offline, front: the wobble, facing you.
const WOBBLE_FRONT = stamp(READY_FRONT, grid(`
  .omttttttttttmo.
  .omtootttootmo..
  .omtottttottmo..
`), 0, 6);

// Front emotes are composed on his own front sprite (MILO.down), so the head is always the vale's:
// a face patch over rows 7–10, and arms drawn over the coat.
const FRONT20 = MILO.down[0].map((r) => `..${r}..`);
const FRONT23 = [...Array(3).fill('.'.repeat(20)), ...FRONT20];
const FACES = {
  happy: ['.omttottttottmo.', '.omtotottototmo.', '.omtkttoottktmo.', '..otttokkottto..'],
  open: ['.omttottttottmo.', '.omttottttottmo.', '.omtkttoottktmo.', '..otttokkottto..'],
};
const withFace = (rows, face, y) => stamp(rows, face, 2, y);
// Both arms up, the lantern held over his right hand (rows of the 23-row front: the hands at 7–8).
const ARMS_UP = grid(`
  ....................
  ................ooo.
  ...............oyyyo
  ...............oiado
  ...............oaado
  ...............oyyyo
  .oo.............ooo.
  otto............otto
  otto............otto
  .oUo............oUo.
  .oUo............oUo.
  .oUo............oUo.
  .oUo............oUo.
  ..oUo..........oUo..
  ...oUo........oUo...
  ...oU..........Uo...
  ....................
  ....................
  ....u..........b....
`);

// Cheer, 1 and 2: both arms up, the lantern shaken high; a grin, then a shout.
const CHEER_A = stamp(withFace(FRONT23, FACES.happy, 10), ARMS_UP, 0, 0);
const CHEER_B = stamp(withFace(FRONT23, FACES.open, 10), ARMS_UP, 0, 0);

// Emotes, facing you.
const WAVE = grid(`
  ..............ott...
  .....oooooo...ottt..
  ...oommmmmmoo..oUo..
  ..ommmmmmmmmmo.oUo..
  .ommmbbmmmmmmmooUo..
  .ommbbmmmmmmmmoUo...
  .omttttmmttttmoUo...
  .omttttttttttmoUo...
  .omttottttottmoUo...
  .omttottttottmoo....
  .omtkttttttktmo.....
  ..otttooootttoo.....
  ...orrrrrrrrro......
  ..ouUUUrrUUUbo......
  .ouuUUUrRUUUbo......
  .ouUUUUUUUUUbo......
  .otUUUUUUUUUbo......
  ..oooooooooooo......
  ....oBBooBBo........
  ....oooooooo........
`);

const THINK = grid(`
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .omttttmmttttmo.....
  .omtottttottttmo....
  .omtottttottttmo....
  .omttttttttttmo.....
  .omtkttttttktmo.....
  ..otttttottto.......
  ...orrrrrottto......
  ..ouUUUrrUottUo.....
  .ouuUUUrRUUooUbo....
  .ouUUUUUUUUUUUbo....
  .otUUUUUUUUUUbo.....
  ..ouUUUUUUUUbo......
  ..oooooooooooo......
  ....oBBooBBo........
  ....oooooooo........
`);

// Laughing: eyes creased shut, mouth open (the clip bounces him).
const LAUGH = withFace(FRONT20, FACES.happy, 7);

const SHRUG = grid(`
  ......oooooo........
  ....oommmmmmoo......
  ...ommmmmmmmmmo.....
  ..ommmbbmmmmmmmo....
  ..ommbbmmmmmmmmo....
  ..omttttmmttttmo....
  ..omttttttttttmo....
  ..omtoottttootmo....
  ..omttttttttttmo....
  ..omtktttttkttmo....
  ...otttoooottto.....
  oo..orrrrrrrro...oo.
  ottoouUUrrUUUbootto.
  .oUUoUUUrRUUUbooUUo.
  ..ooUUUUUUUUUUbooo..
  ...ouUUUUUUUUUbo....
  ...ouUUUUUUUUbo.....
  ...oooooooooooo.....
  .....oBBooBBo.......
  .....oooooooo.......
`);

// Sitting on the ground, facing you, legs crossed; the lantern beside him.
const SIT = grid(`
  ....................
  ....................
  ....................
  .....oooooo.........
  ...oommmmmmoo.......
  ..ommmmmmmmmmo......
  .ommmbbmmmmmmmo.....
  .ommbbmmmmmmmmo.....
  .omttttmmttttmo.....
  .omttttttttttmo.....
  .omttottttottmo.....
  .omttottttottmo.....
  .omtkttttttktmo.....
  ..otttttttttto......
  ...orrrrrrrro...ooo.
  ..ouUUUrrUUUbo.oyyyo
  .ouuUUUrRUUUUbooiado
  .otUUUUUUUUUtooaaado
  .ooBBBBooBBBBooyyyyo
  .ooooooooooooo.oooo.
`);

// Asleep sitting up, facing you: head tipped, eyes shut.
const SLEEP = grid(`
  ....................
  ....................
  ....................
  ......oooooo........
  ....oommmmmmoo......
  ...ommmmmmmmmmo.....
  ..ommmbbmmmmmmmo....
  ..ommbbmmmmmmmmo....
  ..omttttmmttttmo....
  ..omttttttttttmo....
  ..omttttttttttmo....
  ..omtoottttootmo....
  ..omtkttttttktmo....
  ...otttttttttto.....
  ...orrrrrrrro...ooo.
  ..ouUUUrrUUUbo.oyyyo
  .ouuUUUrRUUUUbooddyo
  .otUUUUUUUUUtooddddo
  .ooBBBBooBBBBooyyyyo
  .ooooooooooooo.oooo.
`);

// Camp: asleep in a bedroll by the fire (lying down, seen from the side, the bedroll wood-brown).
const CAMP_SLEEP = grid(`
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  ........................
  .....oooooo.............
  ...oommmmmmoooooooooo...
  ..ommbbmmmmmovvvvvvvvvo.
  .ommbbmmmmmmmovcvvvcvvVo
  .ommmmmmmmtttovvvvvvvvVo
  .ommmmmmtttootovcvvvcvVo
  ..ommmmmtktttovvvvvvvVVo
  ..oooooooooooooooooooooo
`);

export const COAT = Object.freeze({
  rig: 'coat',
  family: 'milo',
  defaultWho: 'milo',
  looks: Object.freeze({ milo: Object.freeze({}) }),
  propKeys: 'adiy',
  placeholders: Object.freeze({ a: 'u', d: 'U', i: 'c', y: 'B' }),
  // His raincoat and scarf's keys (riftfx's OUTFITS.milo): above the neck only these are ever worn
  // (a raised sleeve), so the wear mask keeps his head, and his hair's wood shine, his own; and a
  // patch of them touching only ink, air and the lantern is loose light, never the coat.
  clothes: Object.freeze({ milo: 'uUYrRQ' }),
  // The Clay Likeness's thumbprint is the Scribe's; Milo has none.
  thumbprint: null,
  poses: Object.freeze({
    ready: P(READY, [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [15, 12], back: [4, 14] }),
    'walk.a': P(handPatch(MILO.right[1]), [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [15, 12], back: [4, 14] }),
    'walk.b': P(handPatch(MILO.right[0]), [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [15, 12], back: [4, 14] }),
    'walk.c': P(handPatch(MILO.right[2]), [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [15, 12], back: [4, 14] }),
    'melee.a': P(MELEE_A, [-1, 0], 11, { head: [10, 0], handL: [2, 14], handR: [2, 14], back: [5, 14] }),
    'melee.b': P(MELEE_B, [-7, 0], 12, { head: [13, 1], handL: [3, 6], handR: [3, 6], back: [10, 14] }),
    'melee.c': P(MELEE_C, [-1, 0], 11, { head: [9, 0], handL: [5, 14], handR: [18, 12], back: [4, 14] }),
    'ranged.a': P(RANGED_A, [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [17, 8], back: [4, 14] }),
    'ranged.b': P(RANGED_B, [-1, 0], 11, { head: [8, 0], handL: [4, 14], handR: [17, 11], back: [3, 14] }),
    'cast.a': P(CAST_A, [0, 0], 11, { head: [9, 0], handL: [11, 13], handR: [11, 14], back: [4, 14] }),
    'cast.b': P(CAST_B, [0, -1], 12, { head: [9, 1], handL: [14, 8], handR: [17, 7], back: [4, 15] }),
    gesture: P(GESTURE, [-1, 0], 11, { head: [10, 0], handL: [2, 14], handR: [19, 6], back: [5, 14] }),
    hit: P(HIT, [-1, 0], 11, { head: [7, 0], handL: [4, 14], handR: [13, 13], back: [3, 14] }),
    dodge: P(DODGE, [-2, 0], 11, { head: [6, 0], handL: [3, 14], handR: [11, 13], back: [3, 14] }),
    brace: P(BRACE, [0, 0], 13, { head: [9, 3], handL: [4, 15], handR: [15, 10], back: [3, 15] }),
    jump: P(JUMP, [0, -3], 12, { head: [9, 1], handL: [4, 14], handR: [15, 6], back: [3, 14] }),
    tumble: P(TUMBLE, [-2, -2], 10, { head: [6, 13], handL: [9, 19], handR: [15, 19], back: [14, 15] }),
    wobble: P(WOBBLE, [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [12, 15], back: [4, 14] }),
    doze: P(DOZE, [0, 0], 15, { head: [10, 5], handL: [5, 17], handR: [13, 17], back: [3, 17] }),
    item: P(ITEM, [0, 0], 11, { head: [9, 0], handL: [2, 15], handR: [17, 6], back: [4, 14] }),
    'camp-sit': P(CAMP_SIT, [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [12, 13], back: [4, 14] }),
    'camp-talk': P(CAMP_TALK, [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [17, 7], back: [4, 14] }),
    'camp-job': P(CAMP_JOB, [0, 0], 11, { head: [9, 0], handL: [11, 14], handR: [15, 14], back: [4, 14] }),
    'scarf.a': P(SCARF_A, [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [15, 12], back: [4, 14] }),
    'scarf.b': P(SCARF_B, [-1, 0], 11, { head: [7, 0], handL: [4, 14], handR: [13, 12], back: [3, 14] }),
    'raise.a': P(RAISE_A, [0, 0], 11, { head: [9, 0], handL: [11, 13], handR: [15, 13], back: [4, 14] }),
    'raise.b': P(RAISE_B, [0, -6], 17, { head: [8, 6], handL: [5, 20], handR: [14, 5], back: [4, 20] }),
    'wayward.a': P(WAYWARD_A, [0, 0], 11, { head: [9, 0], handL: [5, 14], handR: [16, 12], back: [4, 14] }),
    'wayward.b': P(WAYWARD_B, [-4, 0], 11, { head: [14, 0], handL: [10, 14], handR: [20, 12], back: [9, 14] }),
    'ready.front': P(READY_FRONT, [0, 0], 11, { head: [8, 0], handL: [2, 15], handR: [13, 15], back: [8, 14] }),
    'walk.front.a': P(WALK_FRONT[1], [0, 0], 11, { head: [8, 0], handL: [2, 15], handR: [13, 15], back: [8, 14] }),
    'walk.front.b': P(WALK_FRONT[0], [0, 0], 11, { head: [8, 0], handL: [2, 15], handR: [13, 15], back: [8, 14] }),
    'walk.front.c': P(WALK_FRONT[2], [0, 0], 11, { head: [8, 0], handL: [2, 15], handR: [13, 15], back: [8, 14] }),
    'wobble.front': P(WOBBLE_FRONT, [0, 0], 11, { head: [8, 0], handL: [2, 15], handR: [13, 15], back: [8, 14] }),
    'cheer.a': P(CHEER_A, [-2, -3], 14, { head: [10, 3], handL: [1, 7], handR: [18, 7], back: [10, 17] }),
    'cheer.b': P(CHEER_B, [-2, -3], 14, { head: [10, 3], handL: [1, 7], handR: [18, 7], back: [10, 17] }),
    wave: P(WAVE, [0, 0], 12, { head: [8, 1], handL: [2, 16], handR: [15, 0], back: [8, 15] }),
    think: P(THINK, [0, 0], 11, { head: [8, 0], handL: [2, 15], handR: [11, 11], back: [8, 14] }),
    laugh: P(LAUGH, [-2, 0], 11, { head: [10, 0], handL: [4, 15], handR: [15, 15], back: [10, 14] }),
    shrug: P(SHRUG, [-1, 0], 11, { head: [9, 0], handL: [1, 12], handR: [18, 12], back: [9, 14] }),
    sit: P(SIT, [0, 0], 14, { head: [8, 3], handL: [2, 17], handR: [13, 17], back: [8, 17] }),
    sleep: P(SLEEP, [0, 0], 14, { head: [9, 3], handL: [2, 17], handR: [13, 17], back: [8, 17] }),
    'camp-sleep': P(CAMP_SLEEP, [-3, 0], 20, { head: [6, 12], handL: [13, 17], handR: [13, 17], back: [14, 17] }),
  }),
  // Small drawings the clips stamp behind the body: a doze's 'z' and the Reboot's blink of light.
  // Exploring: his own walk (sprites.js), for anything that asks the coat rig for it.
  explore: Object.freeze({ down: MILO.down, up: MILO.up, right: MILO.right }),
  overlays: Object.freeze({
    z: Object.freeze(['oooooo', 'occcco', 'oooco.', '.ocooo', 'occcco', 'oooooo']),
    blink: Object.freeze([
      '...c.....c...',
      '.............',
      'u...........u',
      '.............',
      '.............',
      'c...........c',
      '.............',
      '.............',
      '.u.........u.',
      '.............',
      '...c.....c...',
    ]),
  }),
  clips: Object.freeze({
    ready: Object.freeze({
      side: ['ready', 'ready', 'ready', 'ready', ['ready', { op: 'breathe' }], ['ready', { op: 'breathe' }], ['ready', { op: 'breathe' }], 'ready'],
      front: ['ready.front', 'ready.front', 'ready.front', 'ready.front', ['ready.front', { op: 'breathe' }], ['ready.front', { op: 'breathe' }], ['ready.front', { op: 'breathe' }], 'ready.front'],
    }),
    walk: Object.freeze({ side: ['walk.a', 'walk.b', 'walk.c', 'walk.b'], front: ['walk.front.a', 'walk.front.b', 'walk.front.c', 'walk.front.b'] }),
    melee: Object.freeze({ side: ['melee.a', 'melee.b', 'melee.c', 'melee.c', ['melee.c', { op: 'shift', dx: -1, top: 0, bottom: 25 }], 'ready'] }),
    ranged: Object.freeze({ side: [['ranged.a', { op: 'breathe' }], 'ranged.a', 'ranged.b', ['ranged.b', { op: 'nudge', dx: -1 }], 'ready'] }),
    cast: Object.freeze({ side: ['cast.a', 'cast.a', ['cast.a', { op: 'breathe' }], ['cast.a', { op: 'breathe' }], 'cast.a', 'cast.b', 'cast.b', 'ready'] }),
    sustain: Object.freeze({ side: ['cast.a', 'cast.a', ['cast.a', { op: 'breathe' }], ['cast.a', { op: 'breathe' }], 'cast.a', 'cast.a', ['cast.a', { op: 'lift', dy: -1 }], ['cast.a', { op: 'lift', dy: -1 }]] }),
    gesture: Object.freeze({ side: ['ready', 'gesture', ['gesture', { op: 'breathe' }], 'gesture'] }),
    hit: Object.freeze({ side: ['hit', ['hit', { op: 'nudge', dx: -1 }], 'ready'] }),
    dodge: Object.freeze({ side: [['dodge', { op: 'nudge', dx: 1 }], 'dodge', ['dodge', { op: 'nudge', dx: -1 }], 'ready'] }),
    brace: Object.freeze({ side: [['brace', { op: 'lift', dy: -1 }], 'brace'] }),
    jump: Object.freeze({ side: [['ready', { op: 'squash', row: 19 }], 'jump', ['jump', { op: 'lift', dy: 2 }], ['ready', { op: 'squash', row: 19 }]] }),
    tumble: Object.freeze({ side: ['hit', ['tumble', { op: 'lift', dy: -2 }], 'tumble'] }),
    stand: Object.freeze({ side: ['tumble', ['ready', { op: 'squash', row: 20 }], 'ready'] }),
    offline: Object.freeze({
      side: ['wobble', ['wobble', { op: 'shift', dx: 1, top: 0, bottom: 25 }], ['doze', { op: 'lift', dy: -1 }], 'doze', 'doze'],
      front: ['wobble.front', ['wobble.front', { op: 'shift', dx: 1, top: 0, bottom: 25 }], ['sleep', { op: 'lift', dy: -1 }], 'sleep', 'sleep'],
    }),
    dozing: Object.freeze({
      side: [...Array(8).fill('doze'), ...Array(8).fill(['doze', { op: 'breathe', row: 22 }, { op: 'overlay', id: 'z', at: [20, 5] }])],
      front: [...Array(8).fill('sleep'), ...Array(8).fill(['sleep', { op: 'breathe', row: 22 }, { op: 'overlay', id: 'z', at: [22, 7] }])],
    }),
    reboot: Object.freeze({
      side: [['doze', { op: 'overlay', id: 'blink', at: [10, 11] }], ['doze', { op: 'lift', dy: -1 }, { op: 'overlay', id: 'blink', at: [10, 9] }], ['wobble', { op: 'overlay', id: 'blink', at: [10, 7] }], 'wobble', 'ready'],
      front: [['sleep', { op: 'overlay', id: 'blink', at: [10, 11] }], ['sleep', { op: 'lift', dy: -1 }, { op: 'overlay', id: 'blink', at: [10, 9] }], ['wobble.front', { op: 'overlay', id: 'blink', at: [10, 7] }], 'wobble.front', 'ready.front'],
    }),
    item: Object.freeze({ side: ['ready', 'item', ['item', { op: 'breathe' }], 'item', 'ready'] }),
    cheer: Object.freeze({ front: ['cheer.a', 'cheer.b', ['cheer.b', { op: 'lift', dy: -1 }], 'cheer.b'] }),
    wave: Object.freeze({ front: ['wave', 'wave', ['wave', { op: 'shift', dx: 1, top: 0, bottom: 10 }], ['wave', { op: 'shift', dx: 1, top: 0, bottom: 10 }]] }),
    think: Object.freeze({ front: ['think', 'think', 'think', 'think', ['think', { op: 'breathe' }], ['think', { op: 'breathe' }], ['think', { op: 'breathe' }], 'think'] }),
    laugh: Object.freeze({ front: ['laugh', ['laugh', { op: 'lift', dy: -1 }], 'laugh', ['laugh', { op: 'lift', dy: -1 }]] }),
    shrug: Object.freeze({ front: ['ready.front', ['shrug', { op: 'breathe' }], 'shrug', 'shrug'] }),
    sit: Object.freeze({ front: [...Array(8).fill('sit'), ...Array(4).fill(['sit', { op: 'breathe', row: 21 }])] }),
    sleep: Object.freeze({
      front: [...Array(8).fill('sleep'), ...Array(8).fill(['sleep', { op: 'breathe', row: 21 }, { op: 'overlay', id: 'z', at: [22, 7] }])],
    }),
    'camp-sit': Object.freeze({ side: [...Array(8).fill('camp-sit'), ...Array(4).fill(['camp-sit', { op: 'breathe' }])] }),
    'camp-talk': Object.freeze({ side: ['camp-talk', 'camp-talk', ['camp-talk', { op: 'shift', dx: 1, top: 11, bottom: 16 }], 'camp-talk', 'camp-sit', 'camp-sit', 'camp-talk', ['camp-talk', { op: 'breathe' }]] }),
    'camp-sleep': Object.freeze({
      side: [...Array(8).fill('camp-sleep'), ...Array(8).fill(['camp-sleep', { op: 'overlay', id: 'z', at: [10, 12] }])],
    }),
    'camp-job': Object.freeze({ side: ['camp-job', 'camp-job', ['camp-job', { op: 'shift', dx: 1, top: 20, bottom: 24 }], ['camp-job', { op: 'shift', dx: 1, top: 20, bottom: 24 }], 'camp-job', 'camp-job', ['camp-job', { op: 'shift', dx: -1, top: 20, bottom: 24 }], ['camp-job', { op: 'breathe' }]] }),
    // Milo's own clips play in place of cast, so they last its 800 ms: 8 frames at 10 fps.
    scarf: Object.freeze({ side: ['ready', 'scarf.a', 'scarf.a', 'scarf.a', 'scarf.b', 'scarf.b', 'scarf.b', 'ready'] }),
    'raise-lantern': Object.freeze({ side: ['ready', 'raise.a', 'raise.a', 'raise.b', 'raise.b', ['raise.b', { op: 'shift', dx: 1, top: 0, bottom: 8 }], ['raise.b', { op: 'shift', dx: 1, top: 0, bottom: 8 }], 'raise.b'] }),
    'wayward-step': Object.freeze({ side: ['ready', 'wayward.a', 'wayward.a', 'wayward.b', 'wayward.b', ['wayward.b', { op: 'nudge', dx: 1 }], ['wayward.b', { op: 'nudge', dx: 1 }], 'ready'] }),
  }),
});
