// The robe rig (COMBAT.md §14.2): the robed Wayfarers' proportions, 16 × 18 at rest with no legs (a
// hem on an ink row), in a 32 × 28 fight frame with the hem at (16, 26). One body serves the Scribe
// (`claude`) and the Artificer (`codex`): it's drawn in placeholder tones that each look fills in,
//   A robe · D robe shade · F face and hands · H hood shine · T the Scribe's cream nib emblem
//   X the Artificer's cream sash · I the Artificer's book (robe on the Scribe)
// and each of them has their own head (her round hood, his peaked one) and their own held things,
// eight each (her quill, book, pages, ink and letter; his wrench, schematic, gear, rivet and tinkering).
//
// Pose fields as the coat rig's (rows, at, anchors), plus `items`: held things stamped over the body
// at grid points, which the wear mask keeps undressed, and `thumb`, where the Clay Likeness's
// thumbprint goes. A pose built per person is registered as `claude:<pose>` and `codex:<pose>`.
import { grid, stamp } from '../sprites.js';

const f = Object.freeze;
const blank = (w, h) => Array.from({ length: h }, () => '.'.repeat(w));
const layer = (w, h, parts) => parts.reduce((rows, [art, x, y]) => stamp(rows, art, x, y), blank(w, h));

// ---------- heads (16 × 10), per person ----------

const HEAD_SIDE = {
  claude: grid(`
    .....oooo.......
    ...ooAHAAoo.....
    ..oAHHAAAAAo....
    .oAHAAAAAAAAo...
    .oAAAAAAAFFFFo..
    .oAAAAAAFFFFFFo.
    .oAAAAAAFFFFoFo.
    .oAAAAAAFFFFoFo.
    .oAAAAAAFFFFkFo.
    ..oAAAAAAFFFFo..
  `),
  codex: grid(`
    .oo.............
    .oDoo.oooo......
    ..oDAoAAAAoo....
    ..oAAAAAAAAAo...
    .oAAAAAAAFFFFo..
    .oAAAAAAFFFFFFo.
    .oAAAAAAFFFFoFo.
    .oAAAAAAFFFFoFo.
    .oAAAAAAFFFFkFo.
    ..oAAAAAAFFFFo..
  `),
};
const HEAD_FRONT = {
  claude: grid(`
    ......oooo......
    ....ooAAAAoo....
    ...oAHHAAAAAo...
    ..oAHAAAAAAADo..
    ..oAAFFFFFFADo..
    ..oAFFFFFFFFDo..
    ..oAFFoFFoFFDo..
    ..oAFFoFFoFFDo..
    ..oAFkFFFFkFDo..
    ..oAAFFFFFFADo..
  `),
  codex: grid(`
    .........oo.....
    .......ooADo....
    .....ooAAADo....
    ...ooAAAAAADo...
    ..oAAAAAAAAADo..
    ..oAFFFFFFFFDo..
    ..oAFFoFFoFFDo..
    ..oAFFoFFoFFDo..
    ..oAFkFFFFkFDo..
    ..oAAFFFFFFDDo..
  `),
};
// Eyes (side: the eye at (12, 6–7); front: (6, 6–7) and (9, 6–7)).
const SIDE_EYES = {
  shut: [['FFFF', 9, 6], ['FFoo', 9, 7]],
  squeeze: [['FFoF', 9, 6], ['FFFo', 9, 7]],
  swirl: [['Foo', 10, 6], ['FFo', 10, 7]],
};
const FRONT_EYES = {
  shut: [['FFFFFF', 4, 6], ['ooFFoo', 5, 7]],
  happy: [['FoFFoF', 5, 6], ['oFooFo', 5, 7]],
};
function headOf(who, view = 'side', eyes = null) {
  const base = view === 'front' ? HEAD_FRONT[who] : HEAD_SIDE[who];
  const patches = eyes ? (view === 'front' ? FRONT_EYES : SIDE_EYES)[eyes] : null;
  return patches ? patches.reduce((rows, [art, x, y]) => stamp(rows, [art], x, y), base) : base;
}

// ---------- side bodies (facing right; the head stamps over rows 0–9 at `head`) ----------

const SIDE = {
  ready: { head: [0, 0], items: [['hold', 13, 7]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oAAAAAAAAAAAAo.....
    .oATAAAAAAAAAFFo....
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  // walking: the hem swings one way, then the other
  'walk.a': { head: [0, 0], items: [['hold', 13, 7]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oAAAAAAAAAAAAo.....
    .oATAAAAAAAAAFFo....
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAAADo...
    ..oAAAAAAAAAAAADo...
    ..oDDDDDDDDDDDDDo...
    ...ooooooooooooo....
  `) },
  'walk.b': { head: [0, 0], items: [['hold', 13, 7]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oAAAAAAAAAAAAo.....
    .oATAAAAAAAAAFFo....
    .oAAAAAAAAAAAAo.....
    oAAAAAAAAAAAADo.....
    oAAAAAAAAAAAADo.....
    oDDDDDDDDDDDDDo.....
    .ooooooooooooo......
  `) },
  // melee: drawn back, raised, struck
  'melee.a': { head: [0, 0], items: [['back', -2, 11]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oAAAAAAAAAAAAo.....
    oFFAAAAAAAAAAAo.....
    ooATAAAAAAAAAAo.....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  'melee.b': { head: [1, 1], items: [['up', 14, 3]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ...............oo...
    ..oAAAAAAAAAAooFFo..
    .oATAAAAAAAAAAoo....
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  'melee.c': { head: [2, 0], items: [['swing', 17, 11]], rows: grid(`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ....oAAAAAAAAAAoooo.....
    ...oAAAAAAAAAAAAAFFo....
    ..oATAAAAAAAAAAoooo.....
    ..oAAAAAAAAAAAAo........
    .oAAAAAAAAAAAAADo.......
    .oAAAAAAAAAAAAADo.......
    oDDDDDDDDDDDDDDo........
    .ooooooooooooooo........
  `) },
  // ranged: the ink bottle (her) or a rivet (his) aimed, then thrown
  'ranged.a': { head: [0, 0], items: [['throw', 16, 8]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAooo....
    .oAAAAAAAAAAAAAFFo..
    .oATAAAAAAAAAoooo...
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  'ranged.b': { head: [1, 0], items: [['flung', 17, 6]], rows: grid(`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ...oAAAAAAAAAAoooooo....
    ..oAAAAAAAAAAAAAAAFFo...
    ..oATAAAAAAAAAAoooooo...
    ..oAAAAAAAAAAAAo........
    .oAAAAAAAAAAAAADo.......
    .oAAAAAAAAAAAAADo.......
    .oDDDDDDDDDDDDDDo.......
    ..oooooooooooooo........
  `) },
  // cast: the book (her pages, his schematic) open in both hands, then its magic let out
  'cast.a': { head: [0, 0], items: [['book', 11, 10]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oAAAAAAAAAAAAo.....
    .oATAAAAAAAAAAo.....
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  'cast.b': { head: [0, 1], items: [['burst', 15, 1]], rows: grid(`
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    .................oo...
    ..oAAAAAAAAAAooooFFo..
    .oAAAAAAAAAAAAAAoo....
    .oATAAAAAAAAAAoo......
    .oAAAAAAAAAAAADo......
    .oAAAAAAAAAAAADo......
    .oDDDDDDDDDDDDDo......
    ..oooooooooooooo......
  `) },
  // gesture: something held out (a Margin Note, a spare part)
  gesture: { head: [0, 0], items: [['gift', 17, 8]], rows: grid(`
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ..oAAAAAAAAAAoooo.....
    .oAAAAAAAAAAAAAAFo....
    .oATAAAAAAAAAoooFo....
    .oAAAAAAAAAAAAo.o.....
    .oAAAAAAAAAAAADo......
    .oAAAAAAAAAAAADo......
    .oDDDDDDDDDDDDDo......
    ..oooooooooooooo......
  `) },
  hit: { head: [-1, 0], eyes: 'squeeze', items: [['hold', 14, 7]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oAAAAAAAAAAAoo.....
    .oATAAAAAAAAAAFFo...
    .oAAAAAAAAAAAAoo....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  dodge: { head: [-2, 1], items: [['hold', 12, 8]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAo.......
    .oATAAAAAAAAFFo.....
    ..oAAAAAAAAAAAo.....
    ..oAAAAAAAAAAADo....
    ..oAAAAAAAAAAADo....
    ..oDDDDDDDDDDDDo....
    ...oooooooooooo.....
  `) },
  brace: { head: [0, 4], eyes: 'shut', items: [['hold', 14, 9]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAAoo....
    .oATAAAAAAAAAAFFo...
    oAAAAAAAAAAAAAoo....
    oDDDDDDDDDDDDDDo....
    .oooooooooooooo.....
  `) },
  jump: { head: [0, 0], items: [['up', 13, 3]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAoo.....
    .oAAAAAAAAAAAAFo....
    .oATAAAAAAAAAoFo....
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAADo....
    ..oDDDDDDDDDDDDo....
    ...ooooooooooooo....
    ....................
  `) },
  tumble: { head: [-3, 8], eyes: 'swirl', items: [['down', 18, 14]], rows: grid(`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    .............ooooooo....
    ...........ooAAAAAAAo...
    ..........oAAAAAAAAAAo..
    ..........oAAAAAAAAAADo.
    ..........oDAAAAAAAAADo.
    ...........ooDDDDDDDDo..
    .............oooooooo...
  `) },
  wobble: { head: [1, 0], eyes: 'swirl', items: [['down', 14, 15]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ...oAAAAAAAAAAo.....
    ..oAAAAAAAAAAAAo....
    ..oATAAAAAAAAAAo....
    .oAAAAAAAAAAAFFo....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  // dozing: sat down in a heap of robe, head nodded forward, the held thing set down
  doze: { head: [1, 5], eyes: 'shut', items: [['down', 16, 15]], rows: grid(`
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    .oATAAAAAAAAAAAo......
    oAAAAAAAAAAAAFFDo.....
    oDDDDDDDDDDDDDDDo.....
    .ooooooooooooooo......
  `) },
  item: { head: [0, 0], items: [['cordial', 14, 4]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAoo.....
    .oAAAAAAAAAAAAFo....
    .oATAAAAAAAAAoFo....
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAADo....
    .oAAAAAAAAAAAADo....
    .oDDDDDDDDDDDDDo....
    ..oooooooooooooo....
  `) },
  'camp-sit': { head: [0, 2], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oATAAAAAAAAAAo.....
    .oAAAAAAAAAAFFo.....
    .oAAAAAAAAAAAAAAo...
    .oDDDDDDDDDDDDDDo...
    ..oooooooooooooo....
  `) },
  'camp-talk': { head: [0, 2], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ...............oo...
    ..oAAAAAAAAAAooFFo..
    .oATAAAAAAAAAAoFo...
    .oAAAAAAAAAAAAoo....
    .oAAAAAAAAAAAAAAo...
    .oDDDDDDDDDDDDDDo...
    ..oooooooooooooo....
  `) },
  'camp-job': { head: [0, 2], eyes: 'shut', items: [['lap', 9, 12]], rows: grid(`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ..oAAAAAAAAAAo......
    .oATAAAAAAAAAAo.....
    .oAAAAAAAAAAAAo.....
    .oAAAAAAAAAAAAAAo...
    .oDDDDDDDDDDDDDDo...
    ..oooooooooooooo....
  `) },
};

// ---------- front views: the crew's own standing bodies in placeholder tones, and poses on them ----------

const FRONT_BODY = grid(`
  .oAAAAAAAAAAADo.
  .oAAXXXAAATAADo.
  .oAAAAXXXTTTADo.
  .oFAAAAAXXTAAFo.
  .oAAAAAAAAAIIDo.
  ..oAAAAAAAAIIo..
  ..oDDDDDDDDDDo..
  ...oooooooooo...
`);
const FRONT = (who, eyes = null) => layer(16, 18, [[FRONT_BODY, 0, 10], [headOf(who, 'front', eyes), 0, 0]]);
const FRONTW = (who, eyes = null) => FRONT(who, eyes).map((r) => `..${r}..`);
const HEM_SWAY = grid(`
  .oAAAAAAAAAAAADo
  ..oDDDDDDDDDDDo.
  ...ooooooooooo..
`);
// both arms up beside the hood (a 20-wide front), the hands high
const ARMS_UP = grid(`
  .oo..............oo.
  oFFo............oFFo
  oFFo............oFFo
  .oAo............oAo.
  .oAo............oAo.
  .oAo............oAo.
  .oAo............oAo.
  .oAo............oAo.
  .oAo............oAo.
  ..oAo..........oAo..
  ..oAAo........oAAo..
  ...oA..........Ao...
  ....A..........A....
`);
const ARM_UP_RIGHT = ARMS_UP.map((r) => `${'.'.repeat(10)}${r.slice(10)}`);
const ARMS_OUT = grid(`
  oo................oo
  oFFo............oFFo
  .oAAo..........oAAo.
  ..ooAA........AAoo..
`);
const CHIN_HAND = grid(`
  ...........oooo.
  ..........oFFAo.
  ...........oAo..
  ..........oAo...
  ..........AA....
`);
const SIT_BODY = grid(`
  ..oAAAAAAAAAADo.
  .oAAXXXAAATAADo.
  oAAAAAXXXTTTAADo
  oFAAAAAAXXTAAAFo
  oDDDDDDDDDDDDDDo
  .oooooooooooooo.
`);
const BEDROLL = grid(`
  ...ooooooooooooooooooo..
  ..ovvvvvvvvvvvvvvvvvvvo.
  .ovcvvvcvvvcvvvcvvvvvVo.
  .ovvvvvvvvvvvvvvvvvvvVo.
  .ovcvvvcvvvcvvvcvvvVVVo.
  .ooooooooooooooooooooooo
`);

const FRONT_POSES = {
  'ready.front': { at: [0, 0], build: (who) => FRONT(who) },
  'walk.front': { at: [0, 0], build: (who) => stamp(FRONT(who), HEM_SWAY, 0, 15) },
  // The hem stands on the ground row in both cheer frames and the wave (the clip adds the hop).
  'cheer.a': { at: [-2, 0], build: (who) => stamp(FRONTW(who, 'happy'), ARMS_UP, 0, 1) },
  'cheer.b': { at: [-2, 0], build: (who) => stamp(stamp(FRONTW(who, 'happy'), ARMS_UP, 0, 0), ['FooF'], 8, 9) },
  wave: { at: [-2, 0], build: (who) => stamp(FRONTW(who, 'happy'), ARM_UP_RIGHT, 0, 1) },
  think: { at: [-2, 0], build: (who) => stamp(FRONTW(who), CHIN_HAND, 2, 7) },
  laugh: { at: [-2, 0], build: (who) => stamp(FRONTW(who, 'happy'), ['FooF'], 8, 9) },
  shrug: { at: [-2, 0], build: (who) => stamp(FRONTW(who, 'shut'), ARMS_OUT, 0, 10) },
  // A lower head breathes lower (`neck`, the grid row a breath bends at; 8 when the head is at the top).
  sit: { at: [0, 0], neck: 11, build: (who) => layer(16, 18, [[SIT_BODY, 0, 12], [headOf(who, 'front'), 0, 2]]) },
  sleep: { at: [0, 0], neck: 13, build: (who) => layer(16, 18, [[SIT_BODY, 0, 12], [headOf(who, 'front', 'shut'), 0, 3]]) },
  'camp-sleep': { at: [-4, 0], neck: 12, build: (who) => layer(24, 18, [[BEDROLL, 0, 12], [headOf(who, 'side', 'shut'), -1, 4]]) },
};

// ---------- held things, per person (the overlays), stamped at a pose's item points ----------

const ITEMS = {
  claude: {
    // her quill: a cream feather on a wood shaft with an ink nib
    hold: grid(`
      .c.
      cC.
      cC.
      .n.
      .o.
    `),
    back: grid(`
      ccc..
      .cCno
      ...o.
    `),
    up: grid(`
      .c..
      cC..
      .Cc.
      ..n.
      ..no
    `),
    swing: grid(`
      ncCcc
      o..c.
    `),
    // an ink pot, then its ink flung
    throw: grid(`
      .oo.
      oNNo
      oNNo
      .oo.
    `),
    flung: grid(`
      ..N.N
      .NN..
      NNN.N
      .N...
    `),
    // her book of pages, open, then pages let fly
    book: grid(`
      .ooooooo.
      occcocccо
      occcoccco
      oCCCoCCCo
      .kkkokkk.
    `).map((r) => r.replace('о', 'o')),
    burst: grid(`
      c..c....
      .occo.c.
      .occco..
      ..ooo...
      c....c..
    `),
    // a folded letter (a Margin Note)
    gift: grid(`
      oooo
      occo
      oCco
      oooo
    `),
    cordial: grid(`
      .oo.
      okko
      okco
      okko
      .oo.
    `),
    down: grid(`
      cccn
      .ooo
    `),
    // writing on a page on her lap
    lap: grid(`
      oooooooo
      occcocco
      oCCCoCCo
      .......n
    `),
  },
  codex: {
    // his wrench: steel, a dark jaw
    hold: grid(`
      oSo
      oSo
      .s.
      .s.
      .s.
    `),
    back: grid(`
      oo...
      zSsss
      oo...
    `),
    up: grid(`
      oSo.
      .zs.
      ..s.
      ..s.
      ..s.
    `),
    swing: grid(`
      ssSo.u
      ..zSo.
      ...o.u
    `),
    // a rivet, then it flies with sparks
    throw: grid(`
      .oo.
      oSso
      oszo
      .oo.
    `),
    flung: grid(`
      ..u.S
      .u...
      SSs.u
      .u...
    `),
    // his schematic, open, then a gear sent spinning
    book: grid(`
      .ooooooo.
      oEEEoeeeo
      oEcEoecEo
      oEEEoeeeo
      .bbbobbb.
    `),
    burst: grid(`
      u..u....
      .oSSo.u.
      .SzzS...
      .oSSo...
      u....u..
    `),
    // a spare part held out
    gift: grid(`
      .oo.
      oSSo
      oSzo
      .oo.
    `),
    cordial: grid(`
      .oo.
      okko
      okco
      okko
      .oo.
    `),
    down: grid(`
      sssS
      ...z
    `),
    // tinkering with a gadget on his lap
    lap: grid(`
      .u......
      oSSSoooo
      oszSobbo
      .oooo..u
    `),
  },
};

// ---------- assembling the poses ----------

// `neck` is the grid row a breath bends at (breathe and squash sink everything above it): row 8 of
// the head, where the clips' own breaths bend (17 in a standing frame), so it follows the head down.
const pose = (rows, at, anchors, items, thumb, neck) => f({
  rows: f(rows), at: f(at), split: null, neck,
  anchors: f(anchors), items: f(items.map(([id, x, y]) => f({ id, at: f([x, y]) }))), thumb,
});

const POSES = {};
const EXPLORE = {};
for (const who of ['claude', 'codex']) {
  for (const [id, spec] of Object.entries(SIDE)) {
    // A head leaning back past the grid's left edge widens the grid there, so nothing clips.
    const padL = Math.max(0, -spec.head[0]);
    const hx = spec.head[0] + padL;
    const hy = spec.head[1];
    const body = spec.rows.map((r) => '.'.repeat(padL) + r);
    const rows = layer(body[0].length, body.length, [[body, 0, 0], [headOf(who, 'side', spec.eyes || null), hx, hy]]);
    const items = (spec.items || []).map(([item, x, y]) => [item, x + padL, y]);
    const hand = items[0] ? [items[0][1] + 1, items[0][2] + 1] : [13 + padL, 12];
    POSES[`${who}:${id}`] = pose(rows, [-padL, 0], { head: [hx + 7, hy], handL: [3 + padL, 12], handR: hand, back: [3 + padL, 13] }, items, [hx + 12, hy + 8], hy + 8);
  }
  for (const [id, spec] of Object.entries(FRONT_POSES)) {
    const rows = spec.build(who);
    const dx = -spec.at[0];
    POSES[`${who}:${id}`] = pose(rows, spec.at, { head: [dx + 8, 0], handL: [dx + 2, 13], handR: [dx + 13, 13], back: [dx + 8, 13] }, [], [dx + 5, 8], spec.neck ?? 8);
  }
  // Exploration (16 × 18, feet at the bottom middle): the side walk, the front, and a back view.
  const side = (id) => layer(16, 18, [[SIDE[id].rows.map((r) => r.slice(0, 16)), 0, 0], [headOf(who, 'side'), 0, 0]]);
  const back = layer(16, 18, [[FRONT_BODY.map((r) => r.replace(/[XTFI]/g, 'A')), 0, 10], [HEAD_FRONT[who].map((r) => r.replace(/[Fk]/g, 'A').replace(/(?<=A)o(?=A)/g, 'A')), 0, 0]]);
  EXPLORE[who] = f({
    down: f([FRONT(who), stamp(FRONT(who), HEM_SWAY, 0, 15), FRONT(who)].map(f)),
    up: f([back, stamp(back, HEM_SWAY, 0, 15), back].map(f)),
    right: f([side('ready'), side('walk.a'), side('walk.b')].map(f)),
  });
}

const LOOKS = f({
  claude: f({ A: 'r', D: 'R', F: 'c', H: 'k', T: 'c', X: 'r', I: 'r' }),
  codex: f({ A: 'e', D: 'E', F: 't', H: 'e', T: 'e', X: 'c', I: 'b' }),
});

const B = (row = 17) => ({ op: 'breathe', row });
const STEP = ['ready', 'ready', 'ready', 'ready', ['ready', B()], ['ready', B()], ['ready', B()], 'ready'];
const FRONT_STEP = ['ready.front', 'ready.front', 'ready.front', 'ready.front', ['ready.front', B()], ['ready.front', B()], ['ready.front', B()], 'ready.front'];
const Z = (x, y) => ({ op: 'overlay', id: 'z', at: [x, y] });

export const ROBE = f({
  rig: 'robe',
  family: 'who',
  defaultWho: 'claude',
  looks: LOOKS,
  // Each robe's keys (riftfx's OUTFITS): a patch of them that touches only ink, air and what's held
  // is a loose speck, never the robe. The hood is robe too, so there's no neck to keep.
  clothes: f({ claude: 'rRQ', codex: 'eEN' }),
  poses: f(POSES),
  items: f(ITEMS),
  explore: f(EXPLORE),
  overlays: f({
    z: f(['oooooo', 'occcco', 'oooco.', '.ocooo', 'occcco', 'oooooo']),
    blink: f(['...c.....c...', '.............', 'u...........u', '.............', '.............', 'c...........c', '.............', '.............', '.u.........u.', '.............', '...c.....c...']),
  }),
  clips: f({
    ready: f({ side: STEP, front: FRONT_STEP }),
    walk: f({ side: ['walk.a', 'ready', 'walk.b', 'ready'], front: ['walk.front', 'ready.front', ['walk.front', { op: 'shift', dx: -1, top: 24, bottom: 27 }], 'ready.front'] }),
    melee: f({ side: ['melee.a', 'melee.b', 'melee.c', 'melee.c', ['melee.c', { op: 'nudge', dx: -1 }], 'ready'] }),
    ranged: f({ side: [['ranged.a', B()], 'ranged.a', 'ranged.b', ['ranged.b', { op: 'nudge', dx: -1 }], 'ready'] }),
    cast: f({ side: ['cast.a', 'cast.a', ['cast.a', B()], ['cast.a', B()], 'cast.a', 'cast.b', 'cast.b', 'ready'] }),
    sustain: f({ side: ['cast.a', 'cast.a', ['cast.a', B()], ['cast.a', B()], 'cast.a', 'cast.a', ['cast.a', { op: 'lift', dy: -1 }], ['cast.a', { op: 'lift', dy: -1 }]] }),
    gesture: f({ side: ['ready', 'gesture', ['gesture', B()], 'gesture'] }),
    hit: f({ side: ['hit', ['hit', { op: 'nudge', dx: -1 }], 'ready'] }),
    dodge: f({ side: [['dodge', { op: 'nudge', dx: 1 }], 'dodge', ['dodge', { op: 'nudge', dx: -1 }], 'ready'] }),
    brace: f({ side: [['brace', { op: 'lift', dy: -1 }], 'brace'] }),
    jump: f({ side: [['ready', { op: 'squash', row: 20 }], ['jump', { op: 'lift', dy: -3 }], ['jump', { op: 'lift', dy: -1 }], ['ready', { op: 'squash', row: 20 }]] }),
    tumble: f({ side: ['hit', ['tumble', { op: 'lift', dy: -2 }], 'tumble'] }),
    stand: f({ side: ['tumble', ['ready', { op: 'squash', row: 20 }], 'ready'] }),
    offline: f({
      side: ['wobble', ['wobble', { op: 'shift', dx: 1, top: 0, bottom: 24 }], ['doze', { op: 'lift', dy: -1 }], 'doze', 'doze'],
      front: [['ready.front', { op: 'shift', dx: 1, top: 0, bottom: 19 }], ['ready.front', { op: 'shift', dx: -1, top: 0, bottom: 19 }], ['sleep', { op: 'lift', dy: -1 }], 'sleep', 'sleep'],
    }),
    dozing: f({
      side: [...Array(8).fill('doze'), ...Array(8).fill(['doze', B(22), Z(21, 10)])],
      front: [...Array(8).fill('sleep'), ...Array(8).fill(['sleep', B(22), Z(21, 9)])],
    }),
    reboot: f({
      side: [['doze', { op: 'overlay', id: 'blink', at: [10, 12] }], ['doze', { op: 'lift', dy: -1 }, { op: 'overlay', id: 'blink', at: [10, 10] }], ['wobble', { op: 'overlay', id: 'blink', at: [10, 8] }], 'wobble', 'ready'],
      front: [['sleep', { op: 'overlay', id: 'blink', at: [10, 12] }], ['sleep', { op: 'lift', dy: -1 }, { op: 'overlay', id: 'blink', at: [10, 10] }], ['ready.front', { op: 'overlay', id: 'blink', at: [10, 8] }], 'ready.front', 'ready.front'],
    }),
    item: f({ side: ['ready', 'item', ['item', B()], 'item', 'ready'] }),
    cheer: f({ front: ['cheer.a', 'cheer.b', ['cheer.b', { op: 'lift', dy: -1 }], 'cheer.b'] }),
    wave: f({ front: ['wave', 'wave', ['wave', { op: 'shift', dx: 1, top: 0, bottom: 12 }], ['wave', { op: 'shift', dx: 1, top: 0, bottom: 12 }]] }),
    think: f({ front: ['think', 'think', 'think', 'think', ['think', B()], ['think', B()], ['think', B()], 'think'] }),
    laugh: f({ front: ['laugh', ['laugh', { op: 'lift', dy: -1 }], 'laugh', ['laugh', { op: 'lift', dy: -1 }]] }),
    shrug: f({ front: ['ready.front', ['shrug', B()], 'shrug', 'shrug'] }),
    sit: f({ front: [...Array(8).fill('sit'), ...Array(4).fill(['sit', B(20)])] }),
    sleep: f({ front: [...Array(8).fill('sleep'), ...Array(8).fill(['sleep', B(20), Z(21, 9)])] }),
    'camp-sit': f({ side: [...Array(8).fill('camp-sit'), ...Array(4).fill(['camp-sit', B(19)])] }),
    'camp-talk': f({ side: ['camp-talk', 'camp-talk', ['camp-talk', { op: 'shift', dx: 1, top: 19, bottom: 23 }], 'camp-talk', 'camp-sit', 'camp-sit', 'camp-talk', ['camp-talk', B(19)]] }),
    'camp-sleep': f({ front: [...Array(8).fill('camp-sleep'), ...Array(8).fill(['camp-sleep', Z(9, 10)])] }),
    'camp-job': f({ side: ['camp-job', 'camp-job', ['camp-job', { op: 'shift', dx: 1, top: 21, bottom: 25 }], ['camp-job', { op: 'shift', dx: 1, top: 21, bottom: 25 }], 'camp-job', 'camp-job', ['camp-job', { op: 'shift', dx: -1, top: 21, bottom: 25 }], ['camp-job', B(19)]] }),
  }),
});
